// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlAZzwpS9PGPoccNxrR_TTJUzASHLzKNE',
    appId: '1:616919534868:web:91224f3a7506540da3c601',
    messagingSenderId: '616919534868',
    projectId: 'chat-app-a27e8',
    authDomain: 'chat-app-a27e8.firebaseapp.com',
    storageBucket: 'chat-app-a27e8.appspot.com',
    measurementId: 'G-X3BWL111QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDleL9ckunGyJ205XvkG0fS9krUHEkhjcI',
    appId: '1:616919534868:android:f192bbd06b58155ca3c601',
    messagingSenderId: '616919534868',
    projectId: 'chat-app-a27e8',
    storageBucket: 'chat-app-a27e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMZ6_kMNO6eWxwVzimB3Elb4Gt_C0WnQE',
    appId: '1:616919534868:ios:601d829bdc8c353ea3c601',
    messagingSenderId: '616919534868',
    projectId: 'chat-app-a27e8',
    storageBucket: 'chat-app-a27e8.appspot.com',
    iosClientId: '616919534868-i1adi7v52gcajf2pbecq399npm6j9fba.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
